{% set name = "pyddx" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ddsolvation/ddX.git
  git_rev: 9322d0d1f18c7411230e8d9445565977b200f4fd

build:
  skip: true  # [win or py<38]
  script: |
    echo "=== Build debug information ==="
    echo "Build platform: {{ build_platform }}"
    echo "Target platform: {{ target_platform }}"

    {{ PYTHON }} -m pip install . -vv

    echo "=== Listing ALL files in build and site-packages ==="
    echo "--- Build directory contents ---"
    find ./build -type f 2>/dev/null | head -20 || echo "No build dir"
    echo "--- Site-packages contents ---"
    find {{ PREFIX }}/lib/python*/site-packages/ -type f 2>/dev/null | head -20 || echo "No site-packages files"

    echo "=== Checking if .so file exists but with different name ==="
    {{ PYTHON }} -c "
    import os
    import site
    for sp in site.getsitepackages():
        print(f'Checking: {sp}')
        for f in os.listdir(sp):
            if 'pyddx' in f:
                print(f'  Found: {f}')
                full_path = os.path.join(sp, f)
                if os.path.isfile(full_path):
                    print(f'    Is file: {full_path}')
    "
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - make
    - cmake >=3.14
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - pybind11 >=2.6
    - setuptools
    - libblas
    - liblapack
    - numpy
  run:
    - python
    - numpy >=1.14
    - scipy >=1.8

test:
  imports:
    - pyddx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://ddsolvation.github.io/ddX
  summary: ddx continuum solvation library
  dev_url: https://github.com/ddsolvation/ddX
  doc_url: https://ddsolvation.github.io/ddX
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  description: |
    ddX is an open-source software package for continuum solvation models based
    on the domain decomposition paradigm. It contains a common interface for
    the three different methods ddCOSMO, ddPCM and ddLPB for the numerical
    solution to the COSMO, PCM and LPB solvation models. ddX computes for these
    methods the electrostatic contribution to the solvation energy, the
    corresponding contribution to the forces and/or the contribution to the
    Fock- or DFT Kohn-Sham-matrix. Using the common interface, all three
    methods are accessible from a host-code that is used to model the solute
    and which can be on the level of QM, QM/MM, polarizable MM or MM, or as a
    standalone application.

extra:
  recipe-maintainers:
    - mnottoli
    - mfherbst
