{% set name = "pyddx" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ddsolvation/ddx/archive/v{{ version }}.tar.gz
  sha256: b86e05e3c39b8ef977036a4b84c2a845b27ae8f497ba66d97fd4969279d3c24f

build:
  skip: true  # [win or py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - make
    - cmake >=3.14
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - pybind11 >=2.6
    - setuptools
    - libblas
    - liblapack
    - numpy
  run:
    - python
    - numpy >=1.14
    - scipy >=1.8

test:
  imports:
    - pyddx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://ddsolvation.github.io/ddX
  summary: ddx continuum solvation library
  dev_url: https://github.com/ddsolvation/ddX
  doc_url: https://ddsolvation.github.io/ddX
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  description: |
    ddX is an open-source software package for continuum solvation models based
    on the domain decomposition paradigm. It contains a common interface for
    the three different methods ddCOSMO, ddPCM and ddLPB for the numerical
    solution to the COSMO, PCM and LPB solvation models. ddX computes for these
    methods the electrostatic contribution to the solvation energy, the
    corresponding contribution to the forces and/or the contribution to the
    Fock- or DFT Kohn-Sham-matrix. Using the common interface, all three
    methods are accessible from a host-code that is used to model the solute
    and which can be on the level of QM, QM/MM, polarizable MM or MM, or as a
    standalone application.

extra:
  recipe-maintainers:
    - mnottoli
    - mfherbst
