{% set name = "pyddx" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ddsolvation/ddx/archive/v{{ version }}.tar.gz
  sha256: 70dd8acb77491d950d8a0d6fb28abb895b308d704aa207f70b8979121bf282be

build:
  skip: true  # [win or py<38]
  script: |
    echo "=== Build debug information ==="
    find . -name "*pyddx*" -type f 2>/dev/null || echo "No pyddx files found before build"

    {{ PYTHON }} -m pip install . -vv

    echo "=== After build - checking what was created ==="
    find . -name "*pyddx*" -type f 2>/dev/null || echo "No pyddx files found after build"

    # Check the actual site-packages directory
    echo "=== Checking site-packages ==="
    {{ PYTHON }} -c "import site; print('site-packages:', site.getsitepackages())"
    find {{ PREFIX }}/lib/python*/site-packages/ -name "*pyddx*" -type f 2>/dev/null || echo "No pyddx files in site-packages"

    # Try to list the actual extension module
    echo "=== Attempting to import ==="
    {{ PYTHON }} -c "import pyddx; print('SUCCESS: Import worked!'); print(pyddx.__file__)" || echo "IMPORT FAILED"
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - make
    - cmake >=3.14
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - pybind11 >=2.6
    - setuptools
    - libblas
    - liblapack
    - numpy
  run:
    - python
    - numpy >=1.14
    - scipy >=1.8

test:
  imports:
    - pyddx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://ddsolvation.github.io/ddX
  summary: ddx continuum solvation library
  dev_url: https://github.com/ddsolvation/ddX
  doc_url: https://ddsolvation.github.io/ddX
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  description: |
    ddX is an open-source software package for continuum solvation models based
    on the domain decomposition paradigm. It contains a common interface for
    the three different methods ddCOSMO, ddPCM and ddLPB for the numerical
    solution to the COSMO, PCM and LPB solvation models. ddX computes for these
    methods the electrostatic contribution to the solvation energy, the
    corresponding contribution to the forces and/or the contribution to the
    Fock- or DFT Kohn-Sham-matrix. Using the common interface, all three
    methods are accessible from a host-code that is used to model the solute
    and which can be on the level of QM, QM/MM, polarizable MM or MM, or as a
    standalone application.

extra:
  recipe-maintainers:
    - mnottoli
    - mfherbst
